version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app  # Mount server directory to /app in the container
    ports:
      - "8888:8888"
    depends_on:
      - db
    restart: unless-stopped

  websocket:
    build:
      context: ./socket-service
      dockerfile: Dockerfile
    volumes:
      - ./socket-service:/usr/src/app  # Mount socket-service directory to /usr/src/app in the container
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - server
  #     - websocket
  #   restart: unless-stopped

volumes:
  postgres_data:
