version: "3.8"
services:
  db:
    image: postgres:16.3-alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgresDB
    volumes:
      - .:/app

volumes:
  postgres_data:
