name: My Jobs

on: [push]

jobs:
  test:
    runs-on: [self-hosted, some-label]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - run: cd server
      - run: python -m venv env
      - run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install -r server/requirements/dev.txt
      - name: Set environment variables
        run: |
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=60" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "SECRET_KEY=mysecretkey" >> $GITHUB_ENV
          echo "FIREBASE_CONFIG_KEY=fakeKey" >> $GITHUB_ENV
      - name: Unit tests
        run: |
          source env/bin/activate
          sh server/bin/run_tests.sh
