name: My Jobs

on: [push]

jobs:
  test:
    runs-on: [self-hosted, some-label]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Set environment variables
        run: |
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=60" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "SECRET_KEY=mysecretkey" >> $GITHUB_ENV
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > fakseServiceAccountKey.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/fakseServiceAccountKey.json" >> $GITHUB_ENV
      - run: |
          cd server
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Unit tests
        run: |
          cd server
          source venv/bin/activate
          sh bin/run_tests.sh
