name: My Jobs

on: [push]

jobs:
  test:
    runs-on: [self-hosted, some-label]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - run: cd server
      - run: ls -la
      - run: python -m venv env
      - run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Unit tests
        run: |
          source env/bin/activate
          sh server/bin/run_tests.sh
